jenkins:
  systemMessage: 'Jenkins configured automatically by Jenkins Configuration as Code plugin'
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - name: 'Jenkins User'
          id: ${JENKINS_USER}
          password: ${JENKINS_PASSWORD}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

tool:
  git:
    installations:
      - name: git
        home: git
  nodejs:
    installations:
      - name: nodejs
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: '20.14.0'
                    npmPackages: semantic-release@24.0.0 semantic-release-helm3@2.9.3 @commitlint/cli@19.3.0 @commitlint/config-conventional@19.2.2
                    npmPackagesRefreshHours: 360
  go:
    installations:
      - name: 'go'
        properties:
          - installSource:
              installers:
                - golangInstaller:
                    id: '1.22.4'

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: dockerhub
              username: '${DOCKER_HUB_USERNAME}'
              password: '${DOCKER_HUB_PASSWORD}'
              description: 'Docker Hub credentials'
          - usernamePassword:
              scope: GLOBAL
              id: github
              username: 'github'
              password: '${GITHUB_TOKEN}'
              description: 'GitHub credentials'
          - string:
              scope: GLOBAL
              id: github-webhook
              secret: '${GITHUB_TOKEN}'
              description: 'GitHub webhook Token'
          - gitHubApp:
              scope: GLOBAL
              id: 'github-app'
              appID: ${GITHUB_APP_ID}
              privateKey: ${readFile:${GITHUB_APP_ID_PRIVATE_KEY_PATH}}
              description: 'GitHub app'

unclassified:
  githubpluginconfig:
    configs:
      - name: 'GitHub Plugin Configuration'
        credentialsId: 'github-webhook'
        manageHooks: true
  location:
    adminAddress: '${EMAIL}'
    url: https://${DOMAIN}

jobs:
  - file: /var/lib/jenkins/casc_configs/jobs/build-jobs.groovy
  - file: /var/lib/jenkins/casc_configs/jobs/pull-request-jobs.groovy
