name: Packer Validate

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Set up Packer
        id: setup
        uses: hashicorp/setup-packer@main

      - name: Packer init
        id: init
        run: 'packer init .'

      - name: Packer fmt check
        id: fmt
        run: 'packer fmt -check .'

      - name: Export github key
        id: export
        run: 'echo "Hello" > github-app.pem'

      - name: Packer validate
        id: validate
        env:
          PKR_VAR_domain: ${{ secrets.PKR_VAR_domain }}
          PKR_VAR_email: ${{ secrets.PKR_VAR_email }}
          PKR_VAR_jenkins_user: ${{ secrets.PKR_VAR_jenkins_user }}
          PKR_VAR_jenkins_password: ${{ secrets.PKR_VAR_jenkins_password }}
          PKR_VAR_docker_hub_username: ${{ secrets.PKR_VAR_docker_hub_username }}
          PKR_VAR_docker_hub_password: ${{ secrets.PKR_VAR_docker_hub_password }}
          PKR_VAR_github_token: ${{ secrets.PKR_VAR_github_token }}
          PKR_VAR_github_app_id: ${{ secrets.PKR_VAR_github_app_id }}
        run: 'packer validate .'
